In [ ]:
#Python Assignment no: 8

In [1]:
#Write a python program to add Matrices

In [2]:
import numpy as np

In [4]:
a=[[1,2,3],[4,5,6],[10,20,30]]
b=[[23,24,25],[12,23,14],[45,34,20]]
arr1=np.array(a)
print(arr1)
arr2=np.array(b)
print(arr2)
print("addition of two matxix")
add=arr1+arr2
print(add)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
[[23 24 25]
 [12 23 14]
 [45 34 20]]
addition of two matxix
[[24 26 28]
 [16 28 20]
 [55 54 50]]


In [ ]:
#Write a python program to multiply two matrices

In [6]:
x=[[1,2,3],[4,5,6],[10,20,30]]
y=[[23,24,25],[12,23,14],[45,34,20]]
array1=np.array(x)
print(array1)
array2=np.array(y)
print(array2)
print("multiplication of two matxix")
product=arr1*arr2
print(product)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
[[23 24 25]
 [12 23 14]
 [45 34 20]]
multiplication of two matxix
[[ 23  48  75]
 [ 48 115  84]
 [450 680 600]]


In [ ]:
Write a python program to Transpose a Matrix.

In [8]:
x=[[1,2,3],[4,5,6],[10,20,30]]
arr=np.array(x)
print(arr)
print("transpose of matrix")
trans=arr.transpose()
print(trans)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
transpose of matrix
[[ 1  4 10]
 [ 2  5 20]
 [ 3  6 30]]


In [ ]:
#Write a python program to sort a word in alphabetic order?

In [13]:
word=list("happy birthday")
print(word)
word.sort()
print(word)

['h', 'a', 'p', 'p', 'y', ' ', 'b', 'i', 'r', 't', 'h', 'd', 'a', 'y']
[' ', 'a', 'a', 'b', 'd', 'h', 'h', 'i', 'p', 'p', 'r', 't', 'y', 'y']


In [22]:
#example two
sen="This is my eight python assignment"
words=sen.lower().split()
print(words)
words.sort()
print(words)


['this', 'is', 'my', 'eight', 'python', 'assignment']
['assignment', 'eight', 'is', 'my', 'python', 'this']


In [ ]:
#Write a python program to remove punctuation fron string?

In [26]:
puct='''()!@#$%^&*_<>?""::;''{}[]'''
Str=input("Enter your string with punctuation ")
my_sens=""
for i in Str:
    if i not in puct:
        my_sens=my_sens +i
print(my_sens)
        

Enter your string with punctuation hey!! are you ok?? let's join us(:
hey are you ok lets join us
